### ISSUE TITLE
Catch read request from PLC

### ISSUE THREAD

**Issue by remusmp** [Bataide/cip_enip_driver#4]
Hello again,

I see in the examples the driver is used to write data to a PLC. I would like to write data to a PLC when it requests the data. Is there a way to catch the read request from the PLC (along with some payload data)? I could modify the library myself if it's straightforward and any hints would be appreciated. And then my device would reply to the request like in the example provided.

Thanks again,
R.

**Comment by Bataide** [comment]
I would suggest you to use the standard features of the CIP class.
Bind OnConnRecReceiveMsgData event to receive data from PLC, then
call SendData method to send data back to PLC. That way you don't need to
make changes inside the library.

Em qua., 24 de mar. de 2021 às 17:05, Remus Mihail Prunescu <
***@***.***> escreveu:

**Comment by remusmp** [comment]
All good! Works.
